# Site settings
title: "Dies ist der Titel der Webseite"
sitename: "Dies ist der Name der Webseite"
title-divider: " @ "
email: author@schreiben.com
author: "Vorname Name"
description: > # this means to ignore newlines until "baseurl:"
  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima, culpa!
keywords: generelles-keyword1, generelles-keyword2, generelles-keyword3, generelles-keyword4

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://localhost:9999" # the base hostname & protocol for your site
#twitter_username:
#github_username:

# Build settings
markdown: kramdown

source: ./app
destination: ./build

gems:
  - jekyll-sitemap
  - jekyll-paginate

paginate: 5
paginate_path: "/blog/page:num/"

# Gulp takes care of images and assets
exclude: ['img', 'css', 'js', 'fonts', '**.png', '**.jpg', '**.jpeg', '**.gif', '**.webp', '**.svg', '**.ico']

# Don't import the folder structure
exclude: []

include: ['.htaccess', 'robots.txt', 'humans.txt']

# `_config.build.yml` sets `future` and `show_drafts` to `false`
future: true
show_drafts: true
